apiVersion: 1

datasources:
  - name: InfluxDB-Proxmox
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: proxmox-org
      defaultBucket: proxmox-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
